Repository falcosecurity/kilt, pull requests merged in 2021-02, with the labels that each got.

#31 Fix go.mod for utilities to point to correct path
  utilities/launcher/go.mod
  utilities/logshipper/go.mod
  utilities/logshipper/go.sum
  utilities/logshipper/main.go
  utilities/waitforever/go.mod
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/S

#30 Fix duplicate entry point during image command and entry point detection
  runtimes/cloudformation/.gitignore
  runtimes/cloudformation/cfnpatcher/entrypointinfo.go
  runtimes/cloudformation/cfnpatcher/template.go
  runtimes/cloudformation/cmd/cfn-image-info/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#29 Create a debug bridge image for fargate
  utilities/debug-bridge/Dockerfile
  utilities/debug-bridge/Makefile
  utilities/debug-bridge/go.mod
  utilities/debug-bridge/go.sum
  utilities/debug-bridge/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none, size/L

#32 chore(.github): remove release-note block for kilt
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#33 Build binaries with CGO_ENABLED=0
  .gitignore
  installer/Makefile
  runtimes/cloudformation/Makefile
  utilities/launcher/Makefile
  utilities/logshipper/Makefile
  utilities/waitforever/Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#34 Add a utility to track processes liveness and basic stats
  .gitignore
  utilities/debug-bridge/Dockerfile
  utilities/debug-bridge/Makefile
  utilities/debug-bridge/debug-bridge/go.mod
  utilities/debug-bridge/debug-bridge/go.sum
  utilities/debug-bridge/debug-bridge/main.go
  utilities/debug-bridge/process-trace/go.mod
  utilities/debug-bridge/process-trace/go.sum
  utilities/debug-bridge/process-trace/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#35 Improve hints for scratch images
  runtimes/cloudformation/cfnpatcher/entrypointinfo.go
  runtimes/cloudformation/cfnpatcher/template.go
Labels: approved, area/runtime, dco-signoff: yes, kind/bug, lgtm, size/S

#37 better logging for the kilt lambda when using hints
  runtimes/cloudformation/cfnpatcher/patcher.go
  runtimes/cloudformation/cfnpatcher/template.go
Labels: approved, area/cfn-runtime, dco-signoff: yes, kind/feature, lgtm, size/S

#36 process trace - record cpu usage rate
  utilities/debug-bridge/Makefile
  utilities/debug-bridge/process-trace/go.mod
  utilities/debug-bridge/process-trace/go.sum
  utilities/debug-bridge/process-trace/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#38 Fix release process
  .github/workflows/release-kilt-runtimes.yml
  .goreleaser.yml
  runtimes/cloudformation/Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#39 Fix repository hints being ignored
  runtimes/cloudformation/cfnpatcher/template.go
Labels: approved, area/cfn-runtime, dco-signoff: yes, kind/bug, lgtm, size/XS

#40 fix error when installing on non-default regions
  installer/cmd/kilt-installer/cfn-macro.go
  installer/go.mod
  installer/go.sum
  installer/util/aws.go
Labels: approved, area/installer, dco-signoff: yes, kind/bug, lgtm, size/M
